### ISSUE TITLE
Play again creates overlapping text

### ISSUE THREAD

**Issue by YTCuber** [JellyWX/Minesweeper#1]
Ubuntu 16.10

![grafik](https://cloud.githubusercontent.com/assets/20047592/24110083/d56205bc-0d92-11e7-98f9-3299a0d3288e.png)

**Comment by JellyWX** [comment]
Hello, and thanks for reporting this. Did you execute `main` or `main.py` for this issue to occur?

**Comment by JellyWX** [comment]
nevermind, found the issue. will be patched upon next release.

**Comment by JellyWX** [comment]
I believe this issue is fixed. Please confirm for yourself before I close the issue

**Comment by YTCuber** [comment]
Sorry, but it is not fixed for me. I get a syntax error. This is what I did:
I removed the old version and executed the following commands:
```
git clone https://github.com/JellyWX/Minesweeper.git -b master
cd Minesweeper/
python3 main.py
```
I already had git, pygame and python3 installed.
This is what I get:

```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from renderers import *
  File "/home/path/to/Minesweeper/renderers.py", line 102
    if self.
           ^
SyntaxError: invalid syntax
```

**Comment by JellyWX** [comment]
sorry yep, dodgy commit forgot to bug check properly. let me just repackage and ill commit it again

**Comment by JellyWX** [comment]
okay, recommited. please confirm if the bug still exists. many thanks for cooperation

**Comment by YTCuber** [comment]
The syntax error looks fixed.
It looks like this now:
![grafik](https://cloud.githubusercontent.com/assets/20047592/24117200/8cc43c5a-0da9-11e7-907e-f0a850916fd2.png)
It is better, but there still is text on top of the board.
I personally would hide the board and then display the text without the board in the background. You could then add a button "show board", which hides the text and shows the board again.

**Comment by JellyWX** [comment]
the text over the board was intentional; thought it'd be useful if people wanted to screenshot or whatever. however, a modification for this would be easy on my part. thanks for feedback, will consider it

**Comment by YTCuber** [comment]
That is why I suggested the "show board"-button.
As this issue is fixed enough, should we close it?

**Comment by JellyWX** [comment]
yes, ill close it now. thank you for your feedback - ill try and add a show board button for future updates!

**Comment by JellyWX** [comment]
I've incorporated your idea and now you have the option to view the grid after a game. you can also control the grid in every way you could in game; eg scale, move etc..
